name: Pull Request
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  audit:
    name: Audit packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Audit packages
        run: npm audit --audit-level moderate
