name: Pull Request
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  audit:
    name: Audit packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Audit packages
        run: npm audit --audit-level moderate
